### ISSUE TITLE
Как использовать api в командах?

### ISSUE THREAD

**Issue by ozu-kun** [DjHaski/coldybot-py#1]
`napi = None # API VK для прямого доступа (если нужно).`
Что нужно вписать, чтобы использовать апи?

**Comment by DjHaski** [comment]
Из-за моей дикой ленивости, и сырости проекта, я много чего не предусмотрел. Буду рад принять ваш Pull Request, или же могу сам все изменить.

**Comment by DjHaski** [comment]
Добавлено в cbd40f6!
